### ISSUE TITLE
bbl-up v6.2.4 doesn't work with vsphere

### ISSUE THREAD

**Issue by joshzarrabi** [cloudfoundry/bosh-bootloader#268]
We ran 
`bbl --debug --state-dir=/tmp/build/4431eb96/initial-bbl-state up --iaas vsphere --vsphere-vcenter-user user --vsphere-vcenter-password password --vsphere-vcenter-ip ip --vsphere-vcenter-dc dc --vsphere-vcenter-cluster cluster --vsphere-vcenter-rp rp --vsphere-network network --vsphere-vcenter-ds ds --vsphere-subnet subnet` to update our existing 5.11 vsphere director and we got the following go panic error:
```
step: creating jumpbox
panic: Can't have key "vcenter_password" in inlined map; conflicts with struct field [recovered]
	panic: Can't have key "vcenter_password" in inlined map; conflicts with struct field

goroutine 1 [running]:
github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml%2ev2.handleErr(0xc42019fe68)
	/go/src/github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml.v2/yaml.go:164 +0x9f
panic(0xec3420, 0xc42020a820)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml%2ev2.(*encoder).structv.func1()
	/go/src/github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml.v2/encode.go:176 +0x6b3
github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml%2ev2.(*encoder).mappingv(0xc4202d42c0, 0x0, 0x0, 0xc42019fcf0)
	/go/src/github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml.v2/encode.go:196 +0x170
github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml%2ev2.(*encoder).structv(0xc4202d42c0, 0x0, 0x0, 0x10dde20, 0xc42022e900, 0x99)
	/go/src/github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml.v2/encode.go:153 +0x104
github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml%2ev2.(*encoder).marshal(0xc4202d42c0, 0x0, 0x0, 0x10dde20, 0xc42022e900, 0x99)
	/go/src/github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml.v2/encode.go:101 +0x533
github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml%2ev2.Marshal(0x10dde20, 0xc42022e900, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cloudfoundry/bosh-bootloader/vendor/gopkg.in/yaml.v2/yaml.go:153 +0x101
github.com/cloudfoundry/bosh-bootloader/bosh.mustMarshal(0x10dde20, 0xc42022e900, 0x10dde20, 0xc42022e900, 0xc4202de600)
	/go/src/github.com/cloudfoundry/bosh-bootloader/bosh/manager.go:353 +0x35
github.com/cloudfoundry/bosh-bootloader/bosh.(*Manager).GetJumpboxDeploymentVars(0xc420068910, 0xd, 0xc4200135c2, 0x6, 0x7ffc74277d71, 0x7, 0xc420064960, 0x24, 0x0, 0x0, ...)
	/go/src/github.com/cloudfoundry/bosh-bootloader/bosh/manager.go:349 +0x460
github.com/cloudfoundry/bosh-bootloader/bosh.(*Manager).CreateJumpbox(0xc420068910, 0xd, 0xc4200135c2, 0x6, 0x7ffc74277d71, 0x7, 0xc420064960, 0x24, 0x0, 0x0, ...)
	/go/src/github.com/cloudfoundry/bosh-bootloader/bosh/manager.go:128 +0x2e3
github.com/cloudfoundry/bosh-bootloader/commands.Up.Execute(0x1a34d60, 0xc4200e2600, 0x1a36400, 0xc420068910, 0x1a356c0, 0xc4200e2680, 0x1a34020, 0xc42017fc20, 0x1a35720, 0xc420068a50, ...)
	/go/src/github.com/cloudfoundry/bosh-bootloader/commands/up.go:71 +0x4f3
github.com/cloudfoundry/bosh-bootloader/commands.(*Up).Execute(0xc420068aa0, 0xc420001690, 0x0, 0x16, 0xd, 0xc4200135c2, 0x6, 0x7ffc74277d71, 0x7, 0xc420064960, ...)
	<autogenerated>:1 +0xbf
github.com/cloudfoundry/bosh-bootloader/application.App.execute(0xc42017fc50, 0x7ffc74277d41, 0x25, 0x1, 0x7ffc74277d67, 0x2, 0xc420001690, 0x0, 0x16, 0xd, ...)
	/go/src/github.com/cloudfoundry/bosh-bootloader/application/app.go:84 +0x405
github.com/cloudfoundry/bosh-bootloader/application.App.Run(0xc42017fc50, 0x7ffc74277d41, 0x25, 0x1, 0x7ffc74277d67, 0x2, 0xc420001690, 0x0, 0x16, 0xd, ...)
	/go/src/github.com/cloudfoundry/bosh-bootloader/application/app.go:32 +0x63
main.main()
	/go/src/github.com/cloudfoundry/bosh-bootloader/bbl/main.go:242 +0x40d6
```

**Comment by rowanjacobs** [comment]
The workaround for this is to run `bbl plan` before running `bbl up` when upgrading.

This should be safe in almost all circumstances, provided you're using terraform override files, `*-override.sh`, and custom tfvars files for any plan patches.

(A notable circumstance where this falls down is with the GCP bosh lite plan patch, since it directly modifies `cloud-config.yml` and `ops.yml`. We'll be looking into a way to provide a safer version of that patch that doesn't get overwritten when you run `bbl plan` again.)
