### ISSUE TITLE
Asset terraform not found error

### ISSUE THREAD

**Issue by pkothare** [cloudfoundry/bosh-bootloader#393]
I was following the [guide](https://docs.cloudfoundry.org/deploying/common/aws.html) to setup CF with my AWS environment and ran into an issue.

The scripts I ran were run in a PowerShell/CMD shell on a Windows 10 x64 machine. I checked that the environment variables were all setup as necessary. The versions of the downloaded components are as follows:

Terraform: [0.11.9](https://releases.hashicorp.com/terraform/0.11.9/terraform_0.11.9_windows_amd64.zip)
BOSH CLI: [5.3.1](https://github.com/cloudfoundry/bosh-cli/releases/download/v5.3.1/bosh-cli-5.3.1-windows-amd64.exe)
BBL: [6.10.18](https://github.com/cloudfoundry/bosh-bootloader/releases/download/v6.10.18/bbl-v6.10.18_windows.exe)
AWS CLI: [Latest](https://s3.amazonaws.com/aws-cli/AWSCLI64PY3.msi)

When I reach Step 4: Create Infrastructure, Bastion, BOSH Director, and Load Balancers and run the command 

```
bbl plan --iaas aws --aws-access-key-id *** --aws-secret-access-key ***  --aws-region us-east-1 --lb-type cf --lb-cert C:\users\pkothare\desktop\cf\dev.crt --lb-key C:\users\pkothare\desktop\cf\dev.key --lb-domain ***  --state-dir  C:\users\pkothare\desktop\cf\bblstate
``` 

I get the following error:

```
panic: asset: Asset(terraform): Asset terraform not found

goroutine 1 [running]:
github.com/cloudfoundry/bosh-bootloader/terraform/binary_dist.MustAsset(0x1cfe234, 0x9, 0xc042266000, 0x0, 0x0)
        /go/src/github.com/cloudfoundry/bosh-bootloader/terraform/binary_dist/tf_binary_dist_windows_amd64.go:113 +0x135
github.com/cloudfoundry/bosh-bootloader/terraform.installTfBinary(0xc04235ae40, 0x32, 0x1ebf200, 0xc0423740d0, 0x0, 0x0)
        /go/src/github.com/cloudfoundry/bosh-bootloader/terraform/binary_path.go:53 +0x41
github.com/cloudfoundry/bosh-bootloader/terraform.BinaryPathInjected(0x1ebf200, 0xc0423740d0, 0x1ebf200, 0xc0423740d0, 0xc04235ec88, 0x1)
        /go/src/github.com/cloudfoundry/bosh-bootloader/terraform/binary_path.go:35 +0x2f4
github.com/cloudfoundry/bosh-bootloader/terraform.BinaryPath(0xc042266158, 0x6d43ce, 0xc0422661a8, 0x40ff23)
        /go/src/github.com/cloudfoundry/bosh-bootloader/terraform/binary_path.go:16 +0x89
github.com/cloudfoundry/bosh-bootloader/terraform.CLI.RunWithEnv(0x1eab7a0, 0xc0423322a0, 0x1eab7a0, 0xc0423322a0, 0xc0420b0b00, 0x3a, 0x1eab7a0, 0xc042332af0, 0x1cf841f, 0x4, ...)
        /go/src/github.com/cloudfoundry/bosh-bootloader/terraform/cli.go:28 +0x3b
github.com/cloudfoundry/bosh-bootloader/terraform.CLI.Run(0x1eab7a0, 0xc0423322a0, 0x1eab7a0, 0xc0423322a0, 0xc0420b0b00, 0x3a, 0x1eab7a0, 0xc042332af0, 0x1cf841f, 0x4, ...)
        /go/src/github.com/cloudfoundry/bosh-bootloader/terraform/cli.go:24 +0xc9
github.com/cloudfoundry/bosh-bootloader/terraform.Executor.Version(0x1eb5280, 0xc04215b680, 0x1eb5280, 0xc04215b6b0, 0x1eb5240, 0xc042086fc0, 0x1eba140, 0xc0421c9b10, 0x0, 0x1eb07c0, ...)
        /go/src/github.com/cloudfoundry/bosh-bootloader/terraform/executor.go:246 +0x106
github.com/cloudfoundry/bosh-bootloader/terraform.Manager.ValidateVersion(0x1ec3480, 0xc04235e8a0, 0x1eafb20, 0x3f4eb90, 0x1eb52c0, 0xc0421c9eb0, 0xc0423322a0, 0x1eabba0, 0xc04215acf0, 0x0, ...)
        /go/src/github.com/cloudfoundry/bosh-bootloader/terraform/manager.go:60 +0x50
github.com/cloudfoundry/bosh-bootloader/commands.Plan.CheckFastFails(0x1ec3cc0, 0xc0420bac80, 0x1ec0b40, 0xc042332540, 0x1ebd940, 0xc042087380, 0x1eafa00, 0xc042271500, 0x1eaf920, 0xc042271520, ...)
        /go/src/github.com/cloudfoundry/bosh-bootloader/commands/plan.go:65 +0x180
github.com/cloudfoundry/bosh-bootloader/application.App.execute(0xc04235d6b0, 0xc04209cf90, 0x25, 0x0, 0x0, 0x0, 0xc04208a070, 0x4, 0xc0421ab960, 0x0, ...)
        /go/src/github.com/cloudfoundry/bosh-bootloader/application/app.go:82 +0x405
github.com/cloudfoundry/bosh-bootloader/application.App.Run(0xc04235d6b0, 0xc04209cf90, 0x25, 0x0, 0x0, 0x0, 0xc04208a070, 0x4, 0xc0421ab960, 0x0, ...)
        /go/src/github.com/cloudfoundry/bosh-bootloader/application/app.go:32 +0x5f
main.main()
        /go/src/github.com/cloudfoundry/bosh-bootloader/bbl/main.go:290 +0x4eef
```
Any idea on how I should fix/address this issue?

**Comment by zachgersh** [comment]
hey @pkothare - sorry for the delay in answering this. Would you mind trying this again? We are actually embedding a version of terraform (the binary) directly into `bbl` now. We don't really test on windows so I would be interested to see if it is working now.

**Comment by pkothare** [comment]
@zachgersh I'm going to be testing it again pretty soon. Just to clarify should I be downloading terraform as per the documentation, or skip that based on what you mentioned about terraform being directly embedded in bbl?
